### ISSUE TITLE
AMREF Health Africa UK - appearing in both published and pending lists

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#185]
The organisation AMREF Health Africa UK is appearing in both the published and pending lists.

Though its name in the pending list is AMREF UK: https://www.iatiregistry.org/dashboard/pending

They are in fact a publisher.

Please can they be removed from the 'Pending' list.

**Comment by derwas** [comment]
Hey @amy-silcock the publisher that appears on the pending page (amrefuk) is not the same that has been approved (amrefha).

The one on the pending page can be seen through this link (using the identifier of the publisher rather than its name) https://www.iatiregistry.org/publisher/b99aa7de-83f8-42b3-962e-d51d1f4ce0b4

There is an explicit redirect in the code that changes the address of the amrefuk to amrefha.

Can you confirm that I can delete that publisher?

**Comment by derwas** [comment]
To properly investigate the issue please refer to these two API calls:

- https://iatiregistry.org/api/action/organization_show?id=amrefuk
- https://iatiregistry.org/api/action/organization_show?id=amrefha

**Comment by amy-silcock** [comment]
@derwas Yes please to deleting the second Amref account which holds no datafiles

**Comment by derwas** [comment]
Done!

**Comment by amy-silcock** [comment]
Thank you
