### ISSUE TITLE
UNFPA activity file error message

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#198]
Hi,

One of UNFPA's files is displaying error message: 

- https://iatiregistry.org/dataset/unfpa-core

I can download and view this file and it appears fine. How can the error messages be fixed?

Thank you,

Amy

**Comment by andylolz** [comment]
Works for me, too.

Checking the activity streams on the registry (e.g. https://iatiregistry.org/publisher/activity/unfpa), it appears the archiver hasn’t made any updates to any datasets since 23 July. (That might explain the problem here. The error message is old, and the dataset hasn’t been checked again since.)

@derwas does it only run once per week? I think it previously ran daily.

**Comment by derwas** [comment]
Fixed now!

The archiver seems to stop for no reason. Well, there must be a reason but I am not getting any proper logging message!

I am changing the cron job to run in the morning for monitoring its progress for the following few days.

**Comment by amy-silcock** [comment]
This has been fixed with no re-occuring errors since August. Closing for now
