### ISSUE TITLE
Datasets without a publisher can be deleted by any user?

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#221]
Relates to https://twitter.com/andylolz/status/1050122312920514571

The dataset in question (which previously [lived here](https://www.iatiregistry.org/dataset/ciuk-0001)) didn’t have a publisher set, and presumably this meant any user had permission to delete it.

**Comment by andylolz** [comment]
Here are two more examples of datasets without organisations, that I guess anyone could delete:
 * https://iatiregistry.org/dataset/hsa-o1
 * https://iatiregistry.org/dataset/art19-activity

**Comment by derwas** [comment]
@andylolz that s a very good catch!

@amy-silcock can you please check those datasets and update their publishers
As a sysadmin you can recover the deleted dataset after adding the publisher.

I will also wait for your confirmation to disable the creation of datasets without publishers.

**Comment by amy-silcock** [comment]
Hi, thanks both.

I've assigned the three files to what I think is the correct org and made them private.

Questions:

- How does this occur? Files shouldn't be able to be published without being assigned to a publisher account. 
- If the publisher account is deleted, then the files should not then still be public? Not sure if this is still an issue, as the files in question are from 2012, 2013.
- Can we please also add in a setting or something which prevents from people without admin or ownership from deleting a floating file?
- Are there any other occurrences of this?

**Comment by derwas** [comment]
Hi @amy-silcock 

> How does this occur? Files shouldn't be able to be published without being assigned to a publisher account.
> If the publisher account is deleted, then the files should not then still be public? Not sure if this is still an issue, as the files in question are from 2012, 2013.

CKAN allows to create datasets without being owned by an organization. There is a validator that prevents this from happening when creating datasets but as the Data was available since 2013 I suspect that the validator was not active at that time!

The other possible scenario, which is most probably the case here, is  when a publisher gets removed, all its datasets lose the link to it. Even when the organization is recovered, you still need to manually add those datasets to it.

> Can we please also add in a setting or something which prevents from people without admin or ownership from deleting a floating file?

I will check what is possible to do here!

> Are there any other occurrences of this?

I will follow up with an email on this.

**Comment by amy-silcock** [comment]
Thanks @derwas

**Comment by derwas** [comment]
At this stage @amy-silcock removed already hanging datasets.
As part of the archiver upgrade, we will include the detection of datasets without publishers.
