### ISSUE TITLE
Many error messages on the Registry

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#230]
Hi,

I tried to purge the Registry today but received a timeout error, and it didn't compete.

This data file is also showing a fair few error messages. Not sure if it's related to the purging or not? https://iatiregistry.org/dataset/ec-fpi-88

![image](https://user-images.githubusercontent.com/27764077/51028616-dafa8780-158b-11e9-970e-11d6bbeb731a.png)

**Comment by gtkChop** [comment]
504 Gateway error is from nginx timeout frontend, which is set to (30sec). However, It is not recommended increasing nginx timeout. 

Since, purging is a python job even after we get 504 error, when we reload the page for next time all datasets should be purged. However, there are some datasets which can't be purged using the UI due to a database error.

However, these datasets can be deleted/purged by running a paster command in ckan - 

`paster dataset purge <dataset id>
`
As a temporary solution - we will delete unpurged datasets and clear the purge queue by running a paster command in CKAN.

There is a fix coming for this issue, please see [the github issue](https://github.com/ckan/ckan/pull/4399), we will incorporate this fix once it is merged with upstream ckan.

**Comment by gtkChop** [comment]
@amy-silcock 

Is it ok to purge 7 datasets in below link manually?

https://iatiregistry.org/ckan-admin/trash

**Comment by amy-silcock** [comment]
I've just tried to purge manually and get this screen:

![image](https://user-images.githubusercontent.com/27764077/52723804-1bdc2680-2fa6-11e9-92da-5892e7412bbc.png)

And refreshing the page brings back the 7 files.

Yes please to delete them.

**Comment by gtkChop** [comment]
Purge functionality is implemented in staging

**Comment by gtkChop** [comment]
Deployed in production. Please let me know if we are good to run purge command in production. Thanks

**Comment by amy-silcock** [comment]
Hi Swaroop,

Purge is working in staging. I still get a 504  time out error in live. Yes please try it out. Do let us know if we can expect any down time.

Thank you.

**Comment by gtkChop** [comment]
That 504 error is the time out from nginx (which is the recommended setting)- not from the CKAN. So if you refresh the page after a couple of minutes, all dataset should be purged.

This 404 time out error occurs when there is a big list of items to purge which takes more than 30 sec.

**Comment by gtkChop** [comment]
Closing the issue - please reopen if you face any issues.
