### ISSUE TITLE
Error on Acid Survivors Foundation publisher page

### ISSUE THREAD

**Issue by jahnvidave** [IATI/ckanext-iati#233]
Hello,

When trying to go to the publisher page for Acid Survivors Foundation, following the link on the [publishers list](https://iatiregistry.org/publisher) - (https://iatiregistry.org/publisher/_admin), we get a '500 Server Error' message.

It seems that in the past they may have had a different Publisher ID (asfpakistan) (https://iatiregistry.org/publisher/asfpakistan), but this page gives a '404 Not Found' error message.

Please can you investigate this and look into fixing the error?

Thank you, Jahnvi

**Comment by gtkChop** [comment]
@jahnvidave This is solved. Please visit the link - https://iatiregistry.org/publisher/_admin

This error is due to the already existing previous publisher id (asfpakistan). CKAN doesn't delete the old publisher ID instead it will set State as "deleted". Made changes in code to check for the publisher ID's state.

**Comment by gtkChop** [comment]
Please note, publisher id = "_admin" for "Acid Survivors Foundation" needs to be changed to some meaningful name.

**Comment by amy-silcock** [comment]
Thanks for fixing @gtkChop
