### ISSUE TITLE
Server Error - on publisher dataset page

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#251]
Hi, 

BEIS are trying to access their datasets so that they can delete their private ones. However, they are getting this server error:

https://www.iatiregistry.org/dataset/beis-icf-activity-file
![image](https://user-images.githubusercontent.com/27764077/58867242-fccae700-86b1-11e9-90af-8f5f44dc9e32.png)

I can't recreate the error.

Please can you look into this? The zendesk ticket number is: 6069.

Thank you,

Amy

**Comment by gtkChop** [comment]
The dataset has been deleted.

https://www.iatiregistry.org/dataset/beis-icf-activity-file

**Comment by amy-silcock** [comment]
Did you delete them?

**Comment by amy-silcock** [comment]
It's the error that need to be fixed. We need the publisher to be able to delete their own files

**Comment by gtkChop** [comment]
I did not delete any of the dataset.

**Comment by gtkChop** [comment]
There was a server error - this because of the context of the user is not passing to another function.

Fixed in staging. However, needs further testing.

**Comment by gtkChop** [comment]
This error is due to the dcat function "dcat_markup_dataset_show". Where the context of the logged user is not passed hence throwing the error "NotAuthorized" to view/delete private datasets for org admin.

Fixed the error by passing in the context of the logged in user. Should be working now.

Please reopen if this is still an issue. Thanks
