### ISSUE TITLE
BUG: Publishers unable to make any changes to their publisher metadata

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#259]
When I attempt to make a change to publisher metadata (via https://iatiregistry.org/publisher/edit/[publisher_id]) I get the following response:

![Screenshot 2019-07-03 at 14 35 57](https://user-images.githubusercontent.com/464193/60596007-ffe3f080-9d9f-11e9-89e4-4c3e8c1c8601.png)

**Comment by andylolz** [comment]
Specifically, I attempted to change the contact email address. But I think the problem occurs regardless.

I guess a hacky solution would be to make these fields `readonly="readonly"` rather than `disabled="disabled"`. But it would be preferable to handle this server side.

**Comment by andylolz** [comment]
Ah, if I try to resubmit the form, it looks like this is already handler server side (although the wording of the error message refers to the "active dataset" rather than the publisher).

So it should be enough to change `disabled="disabled"` for `readonly="readonly"`.

![Screenshot 2019-07-03 at 14 50 50](https://user-images.githubusercontent.com/464193/60596995-04a9a400-9da2-11e9-89c6-30a73f63cc95.png)

**Comment by andylolz** [comment]
I’ve sent a fix for both bits.

**Comment by amy-silcock** [comment]
Hi @gtkChop 

Looks like the error of data being deleted has cropped up again: https://github.com/IATI/ckanext-iati/issues/252. Please could you look into this as a priority?

Thank you for raising @andylolz

**Comment by gtkChop** [comment]
@andylolz @amy-silcock 
yes, we can change from disabled to read-only and yes there is a validator in serverside so that this validation is true for API calls as well. 
Yes, there is a bug with the validator and I have fixed in staging. Testing on several publishers in staging to make sure everything is good.

I will push the changes to the prod soon.

**Comment by amy-silcock** [comment]
Thanks @gtkChop 

Please can you let me know when I can test on staging too?

**Comment by gtkChop** [comment]
you can test in staging and let me know if you find any issues. Thanks

**Comment by amy-silcock** [comment]
I've had look.

Users should be able to update their Publisher Name,

It's only the publisher id and IATI Org ID we want to be read only.

![image](https://user-images.githubusercontent.com/27764077/60668981-1dc75900-9e65-11e9-8ef9-73cd3a15d388.png)

Also, on staging. As a non admin I can't create a new user account? I just get a server error?

**Comment by gtkChop** [comment]
@amy-silcock I believe the server error is because I was working on the staging at the same time

Test - for these scenarios:

- [ ] Create a new publisher: (access not sysadmin) (pass)
- [ ] A sysadmin makes publisher active (pass)
- [ ] Once the dataset is active org admin should not be allowed to change pub id or org id. (read-only) (pass)
- [ ] Org admin should be allowed to change/edit/update other fields (pass)
- [ ] Org admin should be able to change publisher name (pass)
- [ ] Sysadmin should be able to change publisher or org id (pass)
- [ ] Try to create a new publisher with an already active publisher (org or publisher id should be read-only) (pass)
- [ ] New user account (pass)

**Comment by gtkChop** [comment]
@amy-silcock @JoshStanleyDevInit 
Could you please let me know if this looks good from your side? If so I will push the changes to production. Thanks

**Comment by amy-silcock** [comment]
@gtkChop that's looking good to me. I came across no errors when testing it.

Please do push to production.

**Comment by gtkChop** [comment]
@amy-silcock  Deployed.

**Comment by andylolz** [comment]
Great – works for me! Closing.

Btw I see the changes are on the `production` branch of the derilinx repo, but not currently on this repo.
