### ISSUE TITLE
package_search queries are out of sync

### ISSUE THREAD

**Issue by Ocre42** [IATI/ckanext-iati#261]
This comes from a conversation on [IATI-Registry-Refresher](https://github.com/IATI/IATI-Registry-Refresher/issues/28)

It appears that when querying with `package_search` some of the metadata is out of sync with what it should actually be, as opposed to using `package_show` or `group_show`. This is specially noticeable when looking up the `license_id` for some files.

**Comment by andylolz** [comment]
So for example, the `license_id` here is "odc-pddl":
https://iatiregistry.org/api/3/action/package_show?id=udom-org

…but here, it’s "pddl":
https://iatiregistry.org/api/3/action/package_search?fq=organization:udom

These "pddl" `license_id`s were manually updated by registry admins. I suspect one more step was required in order to make the change propagate everywhere.

I recently made a change to PWYF metadata, and the `license_id` information has now propagated:
https://iatiregistry.org/api/3/action/package_search?fq=organization:pwyf

@gtkChop perhaps you could save the publisher metadata for the other orgs listed here, so that this change propagates to all endpoints:
http://dashboard.iatistandard.org/license/pddl.html

**Comment by gtkChop** [comment]
@andylolz @amy-silcock 

All odc-pddl license should be in sync now - 

Please see below:

- [ ] other-closed - Other (Not Open) - Not used anymore
- [ ] pddl - Open Data Commons Public Domain Dedication and Licence (PDDL) - changed to odc-pddl
- [ ] other-nc - Other (Non-Commercial) - Not used anymore
- [ ] odc-by - Open Data Commons Attribution License - Not used anymore
- [ ] cc-nc - Creative Commons Non-Commercial (Any) - Not used anymore

**Comment by andylolz** [comment]
Excellent – looks resolved to me.

**Comment by gtkChop** [comment]
Please reopen if any issues. Thanks
