### ISSUE TITLE
Publisher issue with a redirect

### ISSUE THREAD

**Issue by amy-silcock** [IATI/ckanext-iati#295]
Hello,

10 months ago a user created an organisation account with the publisher id mcs: https://www.iatiregistry.org/organization/mcs

However, this gets redirected to https://www.iatiregistry.org/organization/mce

I think this happened because they created an account with a publisher id that was already on the redirects list: https://iatiregistry.org/ckan-admin/redirects

For now, please can we give 'mcs' a new publisher id? And can we stop new publisher accounts using publisher ids on the redirects list?

Thank you.

**Comment by gtkChop** [comment]
@amy-silcock 

Thanks for the detailed description.

Fixed now, publisher mcs is changed to **mcs_new** (https://iatiregistry.org/publisher/mcs_new). You can change the name of the publisher to the required name through UI.

```
And can we stop new publisher accounts using publisher ids on the redirects list?
```
Yes, there is a validator which stops the user from creating a publisher with any of the old publisher name. I believe this occurred since we implemented the new feature after the mcs publisher has been created.

Please let me know if you have any questions or need clarification. Thanks.

**Comment by amy-silcock** [comment]
Hi Swaroop,

Thank you for looking into this so quickly and providing an explanation. I've tested by creating a new account and received the appropriate error message.

All looks good!
