### ISSUE TITLE
CKAN 2.9.1 publisher redirects bug

### ISSUE THREAD

**Issue by gtkChop** [IATI/ckanext-iati#304]
CKAN 2.9.1 redirects for publishers (old publisher to new publisher) doesn't work. This looks like a core ckan bug and a workaround would be adding/updating the redirects in Nginx.

**Comment by gtkChop** [comment]
@andreaszenasidi 

Fixed in staging. Please let me know if it's good, I will deploy to production. Thanks

**Comment by andreaszenasidi** [comment]
@gtkChop tested on staging and works as expected.

**Comment by gtkChop** [comment]
@andreaszenasidi 

Deployed.

**Comment by andreaszenasidi** [comment]
@gtkChop There are still some issues but they could be caused by something else. 

Examples from the Redirects list: 
https://iatiregistry.org/publisher/orbis_uk
https://iatiregistry.org/publisher/hwa-zm
https://iatiregistry.org/publisher/ct-admin
https://iatiregistry.org/publisher/finland_mfa
https://iatiregistry.org/publisher/imcw_admin
https://iatiregistry.org/publisher/qrfed
https://iatiregistry.org/publisher/idom_mx
https://iatiregistry.org/publisher/kpmgea

**Comment by gtkChop** [comment]
@andreaszenasidi 

Fixed these. Please let me know if there are any further issues. Thanks

**Comment by andreaszenasidi** [comment]
@gtkChop Tested and did not encounter any more issues. Thank you!
