### ISSUE TITLE
504 Gateway Time-out on the Registry (/dashboard part)

### ISSUE THREAD

**Issue by siemvaessen** [IATI/ckanext-iati#326]
<img width="394" alt="Screenshot 2021-02-23 at 21 23 00" src="https://user-images.githubusercontent.com/961036/108903223-578e3a00-761d-11eb-83eb-c24000a32418.png">

 504 Gateway Time-out on the Registry (21:23 CET)

**Comment by siemvaessen** [comment]
As I am able to see the Registry I think only the /dashboard times out - https://iatiregistry.org/dashboard

**Comment by siemvaessen** [comment]
Wanted to close this as it was working yesterday, but getting that 504 again just now when trying to access https://iatiregistry.org/dashboard.
![Screenshot 2021-02-25 at 10 47 06](https://user-images.githubusercontent.com/961036/109134902-d470ff00-7756-11eb-9d01-7c62f12cff7a.png)

**Comment by siemvaessen** [comment]
Seems to be up and down, still 504 error.

**Comment by siemvaessen** [comment]
Still that 504 when trying to sign into the Dashboard.  Any update on this @andreaszenasidi - sometimes I go here to download a file but keep on bumping into this 504. Thanks!

**Comment by gtkChop** [comment]
@siemvaessen 

Thanks for the reporting. Currently, we have 30 seconds limit. 504 Gateway Time out occurs whenever the site takes more than 30 seconds to load.


This occurs when there are lots of activities were going on the site e.g: harvester, API usages, archiver. Moreover, that activity page either the dataset/activity or dashboard activity is really expensive (Because it has to extract all the revisions history of the datasets and there is also but in core CKAN that we have noticed recently related to the activity page).

If you're looking for the dataset, I would say it's always better to use https://iatiregistry.org/dataset/. (Because this extracts dataset from indexing)

**Comment by gtkChop** [comment]
Closing this. Please see issue #319. Both are related
