### ISSUE TITLE
basicneeds-uganda – archiver has raised a Url Error, but the data is fine

### ISSUE THREAD

**Issue by andylolz** [IATI/ckanext-iati#337]
[This dataset](https://iatiregistry.org/dataset/basicneeds-uganda) shows an error. However, the data appears to be fine. I searched back through [the error history here](https://gist.github.com/codeforIATIbot/f117c9be138aa94c9762d57affc51a64/), and didn’t find an error in the last 2 years.

![Screenshot 2021-03-03 at 22 20 17](https://user-images.githubusercontent.com/464193/109880289-a451c080-7c6e-11eb-9a91-34bf183d15c9.png)

**Comment by andreaszenasidi** [comment]
@andylolz The Archiver shows the metadata error now: 
**Archiver Failed · (June 29, 2021)
Archiver failed to update package due to existing validation error. Unknown country code "UGANDA"** 

I will reach out to the publisher about this because this seems to be the old dataset that should have been deleted. The Ugandan activities are now published in a different [dataset](https://iatiregistry.org/dataset/basicneeds-ug).

**Comment by andreaszenasidi** [comment]
@andylolz this works now, as mentioned in the prev issue this was solved by Derilinx implementing a change when an invalid country code is used this will show as **No country assigned** in the Registry metadata.
